## exceptions or errors that's the same !
try:
    a = int(input("Enter a number: "))
    c = 1/a
except Exception as e:
    print(e)

else: 
    print("We were successful!") # executed when errors don't occur


# # this is my logic ; yo pani milxa
# try:
#     a = int(input("Enter a number: "))
#     print(1/a)
# except:
#     print("We were not successful")

# else:
#     print("We were successful")




